disabled_rules:
  - line_length
  - identifier_name
  - nesting
  - large_tuple
  - function_parameter_count
  - type_name
  - shorthand_operator
  - function_body_length
  - unused_optional_binding
  - file_length
  - switch_case_alignment
excluded:
  - ${PWD}/Pods
